/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS GENERATED AUTOMATICALLY BY CONVEX'S CODE GENERATION TOOL.
 *
 * Generated by convex@1.41.0.
 *
 * The typed module references (e.g. `api.health.ping`) live here in the `.d.ts`
 * (concern #9), built from the actual Convex function modules. The runtime object
 * in api.js is an `anyApi` proxy.
 */
import type * as accounts from "../accounts.js";
import type * as health from "../health.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  accounts: typeof accounts;
  health: typeof health;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
