/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS GENERATED AUTOMATICALLY BY CONVEX'S CODE GENERATION TOOL.
 *
 * Generated by convex@1.41.0.
 *
 * NOTE (Phase 4 / Plan 04-01): `convex codegen` requires a configured/authed
 * CONVEX_DEPLOYMENT in this version, so this is a doc-exact hand-written generated
 * file. It uses `anyApi` (Convex's own helper) so `api.health.ping` is a REAL
 * FunctionReference proxy object (not a bare `{}`) — concern #2. Plan 05's real
 * `npx convex deploy` from packages/convex regenerates this before deploy.
 */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = anyApi;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export const internal = anyApi;
