/* eslint-disable */
/**
 * Generated data model module.
 *
 * THIS CODE IS GENERATED AUTOMATICALLY BY CONVEX'S CODE GENERATION TOOL.
 *
 * Generated by convex@1.41.0.
 *
 * The data model is types-only (see dataModel.d.ts); this runtime module carries
 * no exports. It exists so consumers that resolve `./dataModel.js` succeed.
 */
export {};
